### ISSUE TITLE
Sunbeams shown through blocks

### ISSUE THREAD

**Issue by ASOwnerYT** [Eldeston/ESTN-Shaders#3]
![Minecraft 6_12_2020 9_56_37 AM](https://user-images.githubusercontent.com/23545044/101265350-77def300-37aa-11eb-949c-9cb47998c8ac.png)

**Comment by Eldeston** [comment]
Sir, it's supposed to work like this in sunsets and sunrises.

**Comment by ASOwnerYT** [comment]
Since when do sunbeams show through walls in real life? Is it possible to fix this issue, or do you mean it's not possible to do this in shaders?

**Comment by Peppy8651** [comment]
Yea, this doesn't look good honestly. It's like light is shining through the dark, which feels unnatural. Plus, in the picture, it doesn't even look like sunrise or sunset. Perhaps there should be a way to toggle this on or off.

**Comment by Eldeston** [comment]
> Since when do sunbeams show through walls in real life? Is it possible to fix this issue, or do you mean it's not possible to do this in shaders?

Not possible, shaders in Bedrock are very limited and are not like Java, that's why it's like this.
