### ISSUE TITLE
Purple leaves with bare bones textures

### ISSUE THREAD

**Issue by CheesiestCheese** [Eldeston/ESTN-Shaders#8]
Hello! I recently got this shader and after using it for an hour, my leaves started becoming purple for no reason.
heres what it looks like: https://scontent-hkt1-1.xx.fbcdn.net/v/t1.15752-9/275237904_1162258387646246_5940101937330205843_n.png?_nc_cat=108&ccb=1-5&_nc_sid=ae9488&_nc_eui2=AeFs4is9Vrwz3zbmUT3f81h8cUvRMv5j-oxxS9Ey_mP6jAhpEKrEdBkKifz_siIpwZt1bJvPze2u0pJkx5LKmu1M&_nc_ohc=rzoQSN29q3cAX-xHdjo&_nc_ht=scontent-hkt1-1.xx&oh=03_AVLlhTKbVV4x_URlRg8opWsVhwzSU1DhhgVFUaZCiIbhmQ&oe=6254A961

**Comment by Eldeston** [comment]
Hello, unfortunately this shader is no longer supported for various reasons.
