### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by ReMistic** [Eldeston/ESTN-Shaders#9]
Can you add dynamic shadow like vspe shader for estn shader?

**Comment by Eldeston** [comment]
Such is not possible in Minecraft Bedrock's current engine though Minecraft China exist, on the other hand however, this project is no longer supported and will no longer receive updates.

**Comment by Eldeston** [comment]
Such is not possible in Minecraft Bedrock's current engine though Minecraft China exist, on the other hand however, this project is no longer supported and will no longer receive updates.
